### ISSUE TITLE
Gremlins not appearing in left bar

### ISSUE THREAD

**Issue by ryannealmes** [nhoizey/vscode-gremlins#1]
I am getting a bug where gremlins are not appearing in the left bar. I can see the characters highlighted in red in the file tho.

Any ideas?

**Comment by ryuran** [comment]
@nhoizey same here
I work with it every day but I don't know when gremlins disappear from the side bar.

**Comment by nhoizey** [comment]
I think I've found the issue, and fixed it in v0.5.1 I've just released!

Please let me know if it now works for you, @ryannealmes & @ryuran

**Comment by ryuran** [comment]
Yay, It's fixed.
👏

**Comment by nhoizey** [comment]
\o/
