### ISSUE TITLE
Disable typographic gremlins by default

### ISSUE THREAD

**Issue by kleinfreund** [nhoizey/vscode-gremlins#10]
The extension highlights typographic double quotes (i.e. `“`, `”`) as gremlins.

I can see where this could be harmful, but in my opinion it’s a false negative, as I deliberately use them as quotation characters. I don’t want typographic quote-like characters to be highlighted like that.

I think there needs to be a way to configure this behaviour. In my opinion, highlighting typographic characters shouldn’t even be the default.

**Comment by disaac** [comment]
Please let me know if you remove them from the default as that is specifically why I installed the plugin to spot those little buggers. Many things such as configuration files will cause strange errors when those things are present. They typically end up in code on accident due to a copy and paste from a blog or something. 

I just wish there was an option to zap/remove the gremlins similar to the way ["BBedit"](https://www.barebones.com/support/bbedit/arch_bbedit110.html) allows. I will post that in a separate feature request.

**Comment by nhoizey** [comment]
@kleinfreund sorry, I didn't answer earlier, do you still need a specific configuration for this, or is it fine with the latest versions where you can define your own rules?

**Comment by kleinfreund** [comment]
@nhoizey Thank you for getting back to this.

While one can control the list of characters, I feel that for my particular case, this should not be necessary. I don’t see how quotation mark characters qualify as gremlins. Typographical quotation mark characters can usually be distinquished from straight quote marks (i.e. `"` and `'`) pretty easily while the same is not true for zero width spaces.

**Comment by lydell** [comment]
Hi! I can’t really figure out how to configure this. I also use `“”` (and `‘’`) deliberately, so I’d like to configure them not to be considered as gremlins.

First, I went to settings.json and typed `gremlins.char` and it autocompleted to `"gremlins.characters": { ...DEFAULTS }`. Nice! I tried removing `“”` from there, but it made no difference.

For now I’m using this:

```json
    "gremlins.characters": {
        "0003": {
            "description": "end of text",
            "level": "warning"
        },
        "00a0": {
            "description": "non breaking space",
            "level": "warning"
        },
        "200b": {
            "zeroWidth": true,
            "description": "zero width space",
            "level": "error"
        },
        "200c": {
            "zeroWidth": true,
            "description": "zero width non-joiner",
            "level": "warning"
        },
        "200e": {
            "zeroWidth": true,
            "description": "left-to-right mark",
            "level": "error"
        },
        "201c": {
            "description": "left double quotation mark",
            "level": "info"
        },
        "201d": {
            "description": "right double quotation mark",
            "level": "info"
        },
        "202c": {
            "zeroWidth": true,
            "description": "pop directional formatting",
            "level": "error"
        },
        "202d": {
            "zeroWidth": true,
            "description": "left-to-right override",
            "level": "error"
        },
        "202e": {
            "zeroWidth": true,
            "description": "right-to-left override",
            "level": "error"
        },
        "fffc": {
            "zeroWidth": true,
            "description": "object replacement character",
            "level": "error"
        }
    },
    "gremlins.color_info": "transparent",
    "gremlins.gutterIconSize": "0%"
```

In other words: I’ve marked them as info, made info transparent, changed all other info to warning and removed the gutter icon.

**Comment by kimmosaarinen** [comment]
Rather old post, but nowadays configuring the level as none will omit the issue reported in the gutter and in the problems listing.

```
"gremlins.characters": {
  "2013": {
    "description": "en dash",
    "level": "none"
  }
}
```
