### ISSUE TITLE
[Feature request] Improve description of adding custom characters

### ISSUE THREAD

**Issue by LeCyberDucky** [nhoizey/vscode-gremlins#100]
Hi, 

so I just had a lot of trouble with U+000C. It would be nice if this could be added to the defaults. But the reason I'm actually here is because I had a lot of trouble figuring out how to actually add this as a custom character. The project description mentions _where_ to add custom characters, but it doesn't actually show _how_ to do that. A quick little example would be enough and I think it would be very helpful. Thanks!

**Comment by nhoizey** [comment]
fixed by #101
