### ISSUE TITLE
Missing ranges

### ISSUE THREAD

**Issue by datio** [nhoizey/vscode-gremlins#11]
Seems like unicode characters such as [\<fff8\>](https://unicode-table.com/en/#FFF8) aren't detected.
Would they be inside the scope of this project?

**Comment by datio** [comment]
[Soft hyphens](https://en.wikipedia.org/wiki/Soft_hyphen) don't get detected either.

**Comment by nhoizey** [comment]
@datio hello, sorry for the very late answer, trying to catch up on all opened issues.

These would be useful indeed, but I would like to make Gremlins easily configurable before, so that people have the opportunity to decide which characters to look for.

**Comment by jccr** [comment]
> @datio hello, sorry for the very late answer, trying to catch up on all opened issues.
> 
> These would be useful indeed, but I would like to make Gremlins easily configurable before, so that people have the opportunity to decide which characters to look for.

Is it configurable now?

I just ran into the issue of "soft hyphens"  U+00AD not being detected by gremlin.
I could add it to the config, but if this is useful out of the box I can make a PR.

**Comment by SAbboushi** [comment]
> I just ran into the issue of "soft hyphens" U+00AD not being detected by gremlin.

I just ran into the same issue: I (mistakenly) remembered that all zero-width characters would be detected, but see that nhoizey clearly said "reveals some characters"

**Comment by nhoizey** [comment]
@jccr it is now configurable indeed!

@jccr @SAbboushi I just added soft hyphens to the latest release: https://github.com/nhoizey/vscode-gremlins/commit/6a0d350536b7a7252ae978811deaaed854f36aec

**Comment by nhoizey** [comment]
@datio regarding your initial question about <https://unicode-table.com/en/#FFF8>, did you encounter one of them somewhere? It looks like it's an invalid character, not assigned in unicode.

**Comment by datio** [comment]
@nhoizey not really, I was just curious about invisible characters and wanted to develop a XenForo add-on in the spirit of [this](https://news.ycombinator.com/item?id=16749422) at the time.

I use soft hyphens every day though, so thanks for adding it :￸)

All other invisible characters should be highlighted too in my opinion, but they're not as important as soft hyphens.

**Comment by nhoizey** [comment]
@datio I don't know how to easily list all invisible characters, so I'll keep adding the few that people ask for here.

Thanks for your feedback.
