### ISSUE TITLE
Make Gremlins configurable by the user

### ISSUE THREAD

**Issue by dprice** [nhoizey/vscode-gremlins#12]
I noticed Gremlins was not finding some Unicode characters and had to hand edit extension.js file. It would be great if that configuration was in the Settings so it was far easier to edit and would not require edits to source code.

Thanks for the great extension!
-Derek

**Comment by Mon-Tea** [comment]
I got an exception in my code and after I found that the exception was thrown by an invisible character I searched for an extension that show this invisible chars. It would be great to add invisible Characters by ourself.

**Comment by nhoizey** [comment]
Hello @dprice, sorry for the really late answer.

Thanks for the great suggestion, I will definitely try to do that! 👍

**Comment by nhoizey** [comment]
See https://code.visualstudio.com/api/references/contribution-points#contributes.configuration
