### ISSUE TITLE
[Bug] undefined object when changing active text editor 

### ISSUE THREAD

**Issue by LukasReinhart** [nhoizey/vscode-gremlins#129]
**Describe the bug**
The Developer Tools console throws an error including lengthy trace whenever extension.js:250 (onDidChangeActiveTextEditor) runs with `editor` being `undefined`.

**To Reproduce**
1. Open any valid text editor (e.g. a txt file)
2. Leave the editor without switching to another (e.g. by viewing an extension page)
To see the error, open the developer tools: Help -> Toggle Developer Tools (`Ctrl+Shift+i`)

**Expected behavior**
Silent error handling. More specifically, just ignore the event call if there is no editor defined, as searching for Gremlins would not make sense in such context anyways.

**Screenshots**
![gremlin_error](https://user-images.githubusercontent.com/57132519/92256538-246fb700-eed4-11ea-803f-ecc79cd7d262.png)

**Operating system:**
 - OS: Linux

**Visual Studio Code:**
 - Version 1.48.2

**Gremlins extension:**
 - Version 0.23.0

**Additional context**
The error may occur several times, leading me to believe it does not actually impair the extensions function.

**Comment by nhoizey** [comment]
Good catch, thanks!

I've been able to see this also, will fix ASAP.

**Comment by nhoizey** [comment]
Fixed in 0.23.1, thank again!
