### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TheSench** [nhoizey/vscode-gremlins#139]
**Describe the bug**
Gremlin icons (decorations) disappear when changing to a different document and then changing back.  They need to be repainted.

**To Reproduce**
1. Open a file that has gremlins.
2. Notice the gremlin icons on the sidebar
3. Change tabs to another file
4. Change back to the file with gremlins.
5. Notice that the gremlin icons are gone

**Expected behavior**
Gremlin icons are repainted when returning to a document that has already been processed.

**Screenshots**
![Disappearing Gremlins GIF](https://user-images.githubusercontent.com/9260413/95019239-2abb9500-0632-11eb-82ad-a90f365d6993.gif)

**Operating system:**
 - Windows 10

**Visual Studio Code:**
- Version 1.50.0-insiders

**Gremlins extension:**
Latest source.

**Comment by TheSench** [comment]
I have a fix ready, but it will depend on code modified by PR #138, so I will put it up the fix once that PR is merged or declined.

**Comment by nhoizey** [comment]
I also have this issue on macOS, good catch! 👍

#138 is merged, so you can make this new one.
