### ISSUE TITLE
Add support for unicode U+200C

### ISSUE THREAD

**Issue by arcana261** [nhoizey/vscode-gremlins#17]
Hyaaa

This [annoying character](http://www.fileformat.info/info/unicode/char/200c/index.htm) keeps popping in my go source files :) I'd wish to be able to remove them :dagger:

**Comment by nhoizey** [comment]
@arcana261 hello, sorry for the very late answer, trying to catch up on all opened issues.

This would be useful indeed, but I would like to make Gremlins easily configurable before, so that people have the opportunity to decide which characters to look for.

**Comment by nhoizey** [comment]
Done in 57896e64ac4ceff27388aa90081e96e1247cc866
