### ISSUE TITLE
Add U+202C, U+202D, and U+202E

### ISSUE THREAD

**Issue by MLKrisJohnson** [nhoizey/vscode-gremlins#19]
Please add these Unicode characters to the list:

- U+202C: POP DIRECTIONAL FORMATTING
- U+202D: LEFT-TO-RIGHT OVERRIDE
- U+202E: RIGHT-TO-LEFT OVERRIDE

These are zero-width characters that control text direction.

There are a lot of other characters in the Unicode "Other, Format" category that should be treated similarly: https://www.fileformat.info/info/unicode/category/Cf/list.htm

**Comment by nhoizey** [comment]
@MLKrisJohnson hello, sorry for the very late answer, trying to catch up on all opened issues.

These would be useful indeed, but I would like to make Gremlins easily configurable before, so that people have the opportunity to decide which characters to look for.

**Comment by nhoizey** [comment]
Characters now added to the default configuration.
