### ISSUE TITLE
[Bug] Does not show hair space

### ISSUE THREAD

**Issue by usqr** [nhoizey/vscode-gremlins#199]
**Describe the bug**

**To Reproduce**
1. Paste zero width space inside text
2. does not show gremlin or highlight placing of [zero width space](https://unicode-table.com/en/200B/)

**Expected behavior**
Gremlin should appear in the side and placing of the space should be highlighted

**Operating system:**
 - OS: MacOS
 - Version 11.4

**Visual Studio Code:**
 - Version 1.59.0

**Gremlins extension:**
 - Version 0.26.0

**Comment by TheSench** [comment]
Can you please share your Gremlins configuration?  The zero-width space _is_ highlighted by default.
![image](https://user-images.githubusercontent.com/9260413/129712191-74ccc0dc-05b5-4c21-904e-812f8f5c5158.png)

Here is is in the default configuration:
https://github.com/nhoizey/vscode-gremlins/blob/8586f0475000c939b6ae3a7c4ae4eea7293d0e5d/package.json#L115-L119

Here are some unit tests covering zero-width space:
https://github.com/nhoizey/vscode-gremlins/blob/b2908c00d00997e50b1028b5011d474bed2669d3/extension.test.js#L136-L146

**Comment by usqr** [comment]
:thinking:  made me check and it was actually a [hair space](https://unicode-table.com/en/200A/) not the zero width one

**Comment by TheSench** [comment]
For now, I would recommend changing your `gremlins.characters` configuration in your User Settings and adding the hair space in.  If you find it in the settings UI and click `Edit in settings.json`, it should autofill the default values and then you can simply add another rule for `200a`, similar to the existing one for `200b`.

**Comment by usqr** [comment]
Did exactly that, Thanks for the response.
