### ISSUE TITLE
Add support for: U+200E

### ISSUE THREAD

**Issue by roberteckdale** [nhoizey/vscode-gremlins#22]
This one bit me in the @ss.
```
  '200e': {
    zeroWidth: true,
    description: 'left-to-right mark',
    backgroundColor: 'rgba(255,127,80,.5)',
    overviewRulerColor: 'rgba(255,127,80,1)',
  },
```
[https://unicode-table.com/en/200E/](https://unicode-table.com/en/200E/l)

**Comment by nhoizey** [comment]
@roberteckdale hello, sorry for the very late answer, trying to catch up on all opened issues.

This would be useful indeed, but I would like to make Gremlins easily configurable before, so that people have the opportunity to decide which characters to look for.
