### ISSUE TITLE
Add U+000B line tabulation character

### ISSUE THREAD

**Issue by adrianth** [nhoizey/vscode-gremlins#49]
I just spent the last 30 minutes trying to understand why I had validation errors in a piece of YAML data. Turns out that copying the data from a PowerPoint slide added a 0x0B character, also known as a line "tabulation character" or "vertical tab". I think it's fair to say this character has no business appearing in source code files. Please add it to the default configuration. Here's a [SO question](https://stackoverflow.com/questions/3380538/what-is-a-vertical-tab) with more detail on this character.

**Comment by nhoizey** [comment]
Thanks for the suggestion, will be in next release.
