### ISSUE TITLE
[Feature request] Optionally Show Gremlins in VSCode Problem Pane

### ISSUE THREAD

**Issue by TheSench** [nhoizey/vscode-gremlins#53]
**Is your feature request related to a problem? Please describe.**
When dealing with large files, it is easy to miss the Gremlin icon in the left column.

**Describe the solution you'd like**
It would be nice if there was a configuration option to allow "Gremlins" to also appear in the `Problems` pane of VSCode.  This looks like it can be done via [problemMatchers](https://code.visualstudio.com/docs/editor/tasks#_task-autodetection).

ESLint is an example of another linter that does this:
https://github.com/microsoft/vscode-eslint/blob/ed635ca47bbdefc38589c8946eb34758d6c8ea3a/.vscode/tasks.json

**Comment by nhoizey** [comment]
Fixed by #55
