### ISSUE TITLE
[Feature request] line endings

### ISSUE THREAD

**Issue by tarpdalton** [nhoizey/vscode-gremlins#74]
**Is your feature request related to a problem? Please describe.**
Carriage return (CRLF) line endings cause problems on linux systems

**Describe the solution you'd like**
I want to see if there are any carriage returns (`U+000D`) in a file.
Adding it as a character in the config does not trigger gremlin tracker:
```json
 "000D": {
   "zeroWidth": true,
    "description": "carriage return",
    "level": "error"
 }
```

**Describe alternatives you've considered**
1. [Render Line Endings](https://github.com/medo64/render-crlf/) vscode plugin is a solution where you can identify the line endings in files.

2. You can edit .gitconfig to enforce certain line endings
```bash
#Set LF as your line ending default.
git config --global core.eol lf
#Set autocrlf to false to stop converting between windows style (CRLF) and Unix style (LF)
git config --global core.autocrlf false
```

3. You can edit vscode settings to enforce line endings
```json
"files.eol": "\n",
```

**Additional context**
I'm not sure if this is possible with the vscode api, but it would be helpful. 
Are there other unicode characters that gremlin tracker can't detect?

**Comment by nhoizey** [comment]
I indeed tried to add this character, but it isn't detected, or VS Code doesn't keep it "intact" on my macOS (guessing from https://github.com/Microsoft/vscode/issues/35797).

I don't know any other character this plugin can't detect, but there might be.

I will add the Render Line Endings plugin to the README, thanks for the information.
