### ISSUE TITLE
[Feature request] Add en dash (U+2013) to harmful characters because it looks similar to minus (U+002D)

### ISSUE THREAD

**Issue by rklasen** [nhoizey/vscode-gremlins#94]
**Is your feature request related to a problem? Please describe.**
BibTex fails silently when this caracter is in a *.bib, no error is produced. This isn't gremlins fault of course.

**Describe the solution you'd like**
Gremlin may highlight en dash (–) to not confuse it with dash (-) (depends on font of course)

**Describe alternatives you've considered**
Looking by hand/eye :( 

**Additional context**
None

**Comment by nhoizey** [comment]
Thanks for the suggestion, will be in next release.
